### ISSUE TITLE
Failed in pip install git+https: .../network_wrangler.git

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/client_met_council_wrangler_utilities#10]
@e-lo 
I started on installation, stumbled on this and kinda stuck for the time being.  I'm looking for solutions online but maybe you have seems this before.(?)

What I did following the ReadMe:

1.  Created conda env 'lasso'
2.  Installed rtree
3.  Failed on 
`pip install git+https://github.com/wsp-sag/network_wrangler.git@master#egg=network_wrangler`

I tried 'From GitHub' and 'From Clone', both gave me same error with GDAL:
![image](https://user-images.githubusercontent.com/28812722/63122714-65b5c180-bf75-11e9-8dab-d9b788a5b5f9.png)

I wonder if this is some compatibility issue with geopanda related packages (rtree, shapely, gdal, fiona, pyproj),  I had to [manually specify the wheels](https://geoffboeing.com/2014/09/using-geopandas-windows/) for each of them when I had compatibility issue before.

**Comment by e-lo** [comment]
Have I seen it before?  yes.

`conda install shapely`

See https://github.com/wsp-sag/network_wrangler

LMK if that works!

**Comment by i-am-sijia** [comment]
Tried:

- did not work:
1.  `conda install gdal` before `pip install git+https://github.com/wsp-sag/network_wrangler.git@master#egg=network_wrangler`

- worked:
2. `conda remove gdal`, then manually install geopandas `conda install -c conda-forge geopandas`, then `pip install -e git+https://github.com/wsp-sag/network_wrangler.git@master#egg=network_wrangler`

**Comment by i-am-sijia** [comment]
@e-lo 
Thanks, I'll check that out.  Our comments crossed each other in cyberspace!  I guess my manual installation of geopandas had shapely in place.
