### ISSUE TITLE
write a crosswalk between variables, their sources, and eventual cube network

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/client_met_council_wrangler_utilities#17]

**Comment by e-lo** [comment]
@i-am-sijia I wrote the[ following wiki file](https://github.com/wsp-sag/client_met_council_wrangler_utilities/wiki/Highway-Network) based on the PRD, what I see in the network right now, and our decision to try and keep variable names consistent from their source and using lower_case_full_names if not.

Decision to be made (cc: @DavidOry )
1. do we export a shapefile of a single network with variables for all time periods, or
2. a network with variables that cover all time periods?

This is written for the latter but we can alter for the former easily.

**Comment by i-am-sijia** [comment]
@e-lo For highway nodes, what should the variable names be for `isDriveNode`, `isWalkNode`, `isBikeNode`, `isTranNode` ?

**Comment by i-am-sijia** [comment]
for shst variables, can we keep the variable name as shst's?  for example:
`shstReferenceId` instead of `shstRefId`
`shstGeometryId` instead of `geometryId`

while we have `osm_node_id` for nodes, shall we have `osm_link_id` for links?

for rail access links, shall we name them as `transit_walk_access`?  it's missing in the crosswalk.

**Comment by e-lo** [comment]
> For highway nodes, what should the variable names be for isDriveNode, isWalkNode, isBikeNode, isTranNode ?

I like your version of `bike_node` etc..

**Comment by e-lo** [comment]
> for shst variables, can we keep the variable name as shst's? for example:
> shstReferenceId instead of shstRefId
> shstGeometryId instead of geometryId

I like this idea. Will change in wiki and crosswalk.

**Comment by e-lo** [comment]
> while we have osm_node_id for nodes, shall we have osm_link_id for links?

Sounds good. fixed in wiki

**Comment by e-lo** [comment]
> For rail access links, shall we name them as transit_walk_access? it's missing in the crosswalk.

Is there a reason why rail access links should be different than walk links?

**Comment by e-lo** [comment]
Flag of recent changes for @josiekre and @kulshresthaa

**Comment by i-am-sijia** [comment]
`Is there a reason why rail access links should be different than walk links?`

No good reason, thought CUBE might need them separated out.   I made rail access link `transit_walk_access = 1` as well as `walk_access = 1`.

Checked with @jhelsel11 , seems it's not necessary to have them separate.  I will make them walk links.

**Comment by i-am-sijia** [comment]
@e-lo @jhelsel11 

> `HOV_access` should just be `access` (i noticed you had both, but they should be same variable)

`access` is an [OSM attribute](https://wiki.openstreetmap.org/wiki/Key:access).  9 links have value `hov`.
`HOV_access` is a numeric attribute for CUBE network, to replace the `HOV` in PRD. I gave the 9 links value of 100.

Question: for `access` in the wiki, did you mean to stick to the OSM one?

> `bike` should be `bike_facility`

Do we need this attribute? I thought `BIKE` (in PRD) was needed in old network to flag which links are "bike-able". Our new network has "bike-able" flag as `bike_access = 1`, and a combination of `bike_access`, `drive_access`, `walk_access` can tell either dedicated bike or regular bike lane.
