### ISSUE TITLE
Identify or calculate Area Type

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/client_met_council_wrangler_utilities#29]
The default area type variable is specified as `COMDES2040`
...but the default shapefile for calculating area type only has the following variables:

'TAZ', 'POP2010', 'POPINHH10', 'PPH10', 'POPINGQ10', 'HH2010',
       'EMP2010', 'NRET2010', 'RETAIL2010', 'POP2014', 'POPINHH14', 'PPH14',
       'POPINGQ14', 'HH2014', 'EMP2014', 'NRET2014', 'RETAIL2014', 'POP2020',
       'POPINHH20', 'PPH20', 'POPINGQ20', 'HH2020', 'EMP2020', 'NRET2020',
       'RETAIL2020', 'POP2030', 'POPINHH30', 'PPH30', 'POPINGQ30', 'HH2030',
       'EMP2030', 'NRET2030', 'RETAIL2030', 'POP2040', 'POPINHH40', 'PPH40',
       'POPINGQ40', 'HH2040', 'EMP2040', 'NRET2040', 'RETAIL2040', 'TCFLAG',

1. is there a formula we are missing for area type that we should include?
2. or do we have the wrong shapefile?

**Comment by i-am-sijia** [comment]
I did not get this error when testing.

the [default](https://github.com/wsp-sag/client_met_council_wrangler_utilities/blob/b6278d8cb8f5bdb129d5aacf6ffbc757b147d3b1/lasso/Parameters.py#L327) shapefile is [ThriveMSP2040CommunityDesignation.shp](https://github.com/wsp-sag/client_met_council_wrangler_utilities/blob/b6278d8cb8f5bdb129d5aacf6ffbc757b147d3b1/lasso/Parameters.py#L82), which has `COMDES2040`

It seems like you are testing with TAZ shapefile?

**Comment by e-lo** [comment]
Akk - you are right. So embarrassing. I had refactored part of the code an in the process auto-complete made it use the tazshapefile. Sorry about that! (closing now)

**Comment by i-am-sijia** [comment]
haha no need to apologize at all!  It's good to check.
