### ISSUE TITLE
Lasso Project Notebook Fails

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/client_met_council_wrangler_utilities#32]
When I execute this block:

```
test_roadway_project = Project.create_project(
        base_roadway_dir=os.path.join(EX_DIR,"stpaul"),
        roadway_log_file=os.path.join(EX_DIR,"cube","st_paul_test.log"),
    )
```

It *appears* that `build_transit_network` needs to be set to `None` [here](https://github.com/wsp-sag/client_met_council_wrangler_utilities/blob/9c035c18cc9ae4c1167879d29642043051d7a876/lasso/project.py#L105).

**Comment by e-lo** [comment]
Not sure how I missed that. Should be GTG now.
