### ISSUE TITLE
Add ability to write out a fixed-format file instead of a CSV

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/client_met_council_wrangler_utilities#40]
For easier read-in to cube, write highway network to fixed format and also write out the appropriate `FILEI LINKI` read statement at the same time. 

 @jhelsel11  will provide an example script

**Comment by e-lo** [comment]
Test works for me and outputs files. @jhelsel11 are you able to run the cube script and import the network ok?

**Comment by jhelsel11** [comment]
Yes. This issue is resolved.
