### ISSUE TITLE
Set github token in travis-ci to enable it to build documentation

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/client_met_council_wrangler_utilities#42]
On `develop` branch...

In order to deploy documentation to github pages, need to set $GITHUB_TOKEN  in the Travis CI settings page of the repository as a secure variable per: https://docs.travis-ci.com/user/deployment/pages/

Can copy what was done for network_wrangler

**Comment by DavidOry** [comment]
Okay. I *think* it's set up. Please have a look and lemme know if it's working before closing.

**Comment by e-lo** [comment]
Confirmed working as: https://wsp-sag.github.io/client_met_council_wrangler_utilities/
