### ISSUE TITLE
Where does .net --> roadway network standard happen?

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/client_met_council_wrangler_utilities#6]
Have you guys started a separate process for translating between .net files and roadway network standard in a modularized way or should we add that functionality here?

**Comment by DavidOry** [comment]
That currently happens in a Cube script at the beginning of the Met Council model run. Even though this package works with Cube-formatted objects, I'd like to make it not dependent on Cube software, which we'd need to do to write out `.net` files, no?

**Comment by e-lo** [comment]
It makes sense to separate out the cube license part...but what about the translation part between the output csvs/dbfs, and the standard network formats?

**Comment by DavidOry** [comment]
I'm not sure what you mean. Right now, @i-am-sijia is writing out the standard network as CSVs as well as SHPs. @jhelsel11 I think is now reading in the SHP file to create the `.net` file. Is that right John? We gave up on the CSVs to retain the geometries to make editing in Cube easier. So yes, we could add the standard network to shape method here (though it may just be a line of code).

**Comment by e-lo** [comment]
> @i-am-sijia is writing out the standard network as CSVs as well as SHPs.

Yes, this part. Where is this part happening because it will be a necessary step to get from what MetCouncil is coding with in Cube (.net and .log) --> Project Cards

We had talked about modularizing it and just wanted to understand if that was happening under some other umbrella or not.

**Comment by i-am-sijia** [comment]
After I write out network database (GeoDataFrame) to SHPs for John (no longer writing out to CSV),  I have a separate notebook to translate the GeoDataFrame into network standard with required fields, and then write out the geojson/json files.
