### ISSUE TITLE
LogFile -->ProjectCard method for roadway feature change

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/client_met_council_wrangler_utilities#7]
Create method `to_ProjectCard()` in the Log File object that writes project cards:
- [x] `import ProjectCard from network_wrangler`
- [x] consume base network using network wrangler if needed:
```
import RoadwayNetwork from network_wrangler
net = RoadwayNetwork(path/to/net)
```
- [x] does any necessary translation between data in the log file object and what the project card object's `__init__()` method is expecting (a nested dict)
- [ ] validates that it conforms to the ProjectCard schema (see [example for yml](https://github.com/wsp-sag/network_wrangler/blob/bb177a54c5ea00299cb0427c7ba830c6d3056fbf/network_wrangler/ProjectCard.py#L55), but should be able to do directly to the dict) 
- [x] instantiates a new ProjectCard object with the expected data `my_projectcard = ProjectCard(myData)` 
- [x] writes project card skeleton to .yml

For this initial pass, do the simplest example: roadway feature change

**Comment by i-am-sijia** [comment]
@e-lo 
I started testing add_highway_changes() function in pytest.  Please see commit [765b7e1](https://github.com/wsp-sag/client_met_council_wrangler_utilities/commit/765b7e1eb52c82b160e1b0414fbd5426a684ae21) for my latest scripts.

Got an error when calling read_logfile in the python object.  The read_logfile() function was fine when tested alone.

![image](https://user-images.githubusercontent.com/28812722/65050801-fc3f1f00-d935-11e9-9ed7-eac7fb3120f1.png)

**Comment by e-lo** [comment]
See latest, it should address that plus a few other bugs I found.

I left this for you to fix, though:

```python
lasso/project.py:240: NameError


>       changeable_col = [x for x in link_add_df.columns if x in link_add_df.columns]
E       NameError: name 'link_add_df' is not defined
````
